name: Docs

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2
      -   name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.11
      -   name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r doc/requirements.txt --user
      -   name: Build
          run: |
            cd doc && sphinx-build -W -b html -d _build/doctrees . _build/html
